# Generated by Django 6.0.3 on 2026-03-25 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('plant_tree', 'Plant Tree'), ('cycle_commute', 'Cycle Commute'), ('clean_area', 'Clean Area'), ('reduce_plastic', 'Reduce Plastic')], max_length=50)),
                ('credits_reward', models.IntegerField(default=50)),
                ('valid_date', models.DateField()),
                ('sponsor_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EcoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='actions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('credits_awarded', models.IntegerField(default=0)),
                ('co2_kg_offset', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='action.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_confidence', models.FloatField(default=0.0)),
                ('detected_labels', models.JSONField(default=list)),
                ('verification_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('flagged', 'Flagged')], max_length=20)),
                ('duplicate_detected', models.BooleanField(default=False)),
                ('gps_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='action.ecoaction')),
            ],
        ),
    ]
